[package]
name = "poisson-visualisation"
version = "0.1.0"
authors = ["WaDelma <>"]
edition = "2024"

[dependencies]
nalgebra = { version = "0.34.1", features = ["alga", "rand"] }
image = "0.25.8"
clap = "4.5.48"
rand = "0.9.2"
lab = "0.11.0"
fnv = "1.0"
poisson = { path = "../poisson" }