[package]
name = "poisson-visualisation"
version = "0.1.0"
authors = ["WaDelma <>"]
edition = "2018"

[dependencies]
nalgebra = "0.34.1"
image = "0.25.8"
clap = "4.5.48"
rand = "0.9.2"
lab = "0.11.0"
fnv = "1.0"
poisson = { path = "../poisson" }